# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: "metrics[bot]"
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["ajhalili2006/main"]}
jobs:
  github-metrics:
    name: GitHub Metrics Generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ajhalili2006-experiments/gh-metrics-patches@ajhalili2006/main
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ajhalili2006
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: Asia/Manila
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 50
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: Kuys_Potpot
          plugin_tweets_token: ${{secrets.TWITTER_BEARER_TOKEN}}
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_token: ${{secrets.WAKATIME_TOKEN}}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
          plugin_music_provider: spotify
          plugin_music_token: ${{secrets.SPOTIFY_API_TOKEN}}
          plugin_music_mode: recent
