name: "Fetch GitHub activity to profile README"

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read
    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
      
      - name: Update my GH activity section
        uses: RecapTime/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 25
