name: "Pull GH actiity and commit to the README"

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Update my GH activity section
        uses: MadeByThePinsHub/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 25
